In [3]:
import seaborn as sns
import matplotlib.pyplot as plt



In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('PythonExampeData.txt', sep="#", header=0)

print(df.head())

#plt.boxplot(df, column = ['Glucose'], by=['Outcome'])
df.boxplot(column = ['Glucose'], by=['Outcome'])
#df.boxplot(column = ['Outcome'], by=['Glucose'])
plt.xlabel('Diabetic Condition')
plt.ylabel('Glucose Level')
plt.show()

FileNotFoundError: [Errno 2] No such file or directory: 'PythonExampeData.txt'

In [27]:
bins = [0, 80, 90, 120, 200]
bin_labels = ['Normal', 'High Blood Pressure 1', 'High Blood Pressure 2', 'Hypertensive']
bp_status = pd.cut(df.BloodPressure, bins=bins).value_counts() 
bp_status.index = bin_labels
print(bp_status)






Normal                   3
High Blood Pressure 1    0
High Blood Pressure 2    0
Hypertensive             0
Name: count, dtype: int64


In [42]:
df_new_features = pd.read_csv('newFeatures.csv', index_col=0)
print(df_new_features)

combined = df.merge(df_new_features, on='patient_id').sort_values(by=['Age','BMI'])
print(combined)



             BMI  Age
patient_id           
30          34.1   38
430         35.0   43
259         25.9   24
103         22.5   21
525         31.6   24
163         22.5   31
187         22.5   21
   patient_id  Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  \
1         187            8      181             68             36      495   
0         163            0      114             80             34      285   

   DiabetesPedigreeFunction  Outcome   BMI  Age  
1                     0.615        1  22.5   21  
0                     0.167        0  22.5   31  


In [39]:
working_age = combined.Age <= 65
combined_filtered = combined[working_age].sort_index()

print(combined_filtered)


   patient_id  Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  \
0         163            0      114             80             34      285   
1         187            8      181             68             36      495   

   DiabetesPedigreeFunction  Outcome   BMI  Age  
0                     0.167        0  22.5   31  
1                     0.615        1  22.5   21  


In [2]:
import recordlinkage

ModuleNotFoundError: No module named 'recordlinkage'

In [1]:
from thefuzz import fuzz
fuzz.WRatio('Reading', 'Reeding')


86

In [2]:
import torch
import sys
print(f"Python version: {sys.version}")
print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
print(f"CUDA version: {torch.version.cuda}")
print(f"GPU device: {torch.cuda.get_device_name(0)}")


Python version: 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]
PyTorch version: 2.6.0+cu118
CUDA available: True
CUDA version: 11.8
GPU device: NVIDIA GeForce RTX 3060


In [ ]:
x = [8, 'M', 'N', 3, 1, 'A']
print(x)
integers_only = [j if type(j) == int else 0 for j in x]
print(integers_only)
The problem was that you included an extra comma after else 0, which creates invalid syntax. In Python list comprehensions, the conditional expression should be written as expression if condition else alternative for item in iterable.
Alternatively, if you wanted to filter out non-integers completely (rather than replacing them with 0), you could use:

In [8]:
 x = [8, 'M', 'N', 3, 1, 'A']
print (x)
integers_only = [j if type(j) == int else 0 for j in x]
print(integers_only)

[8, 'M', 'N', 3, 1, 'A']
[8, 0, 0, 3, 1, 0]


In [10]:
x = [1,2,3,4]
mult = {i:3 * x for i in x}
print(mult)

{1: [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4], 2: [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4], 3: [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4], 4: [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]}


In [3]:
import numpy as np
np_2d = np.array([[5, 6, 1, 2, 3, 4],
                 [4, 5, 3, 2, 1, 8],
                 [9, 10, 3, 7, 6, 5]])

print(np_2d)
print(np.median(np_2d[0,:]))

[[ 5  6  1  2  3  4]
 [ 4  5  3  2  1  8]
 [ 9 10  3  7  6  5]]
3.5


In [1]:
import torch
print(f"CUDA available: {torch.cuda.is_available()}")
print(f"CUDA version: {torch.version.cuda}")
print(f"GPU device: {torch.cuda.get_device_name(0)}")


ModuleNotFoundError: No module named 'torch'

In [4]:
import numpy as np
np_hights = np.array([[1.6,1.75],[1.56,1.70],[1.49,1.68]])
print(np.mean(np_hights[:,0]))

1.55


In [9]:
import numpy as np
np_array = np.array([1,2,3])
print(np_array)
print(type(np_array))

[1 2 3]
<class 'numpy.ndarray'>


In [6]:
x = ['Mick', 'Leonard','Gorilla']
y = [23,62,94]
list = zip(x,y)
new_dict = dict(list)
print(new_dict)

#for x, y in enumerate(flash_vil):
 #   print(str(x) + ':' +y)



{'Mick': 23, 'Leonard': 62, 'Gorilla': 94}


In [9]:
superhero_list = ['thor', 'hulk']

def to_upper(heroes):
    for i in heroes:
        yield i.upper()

print(list(to_upper(superhero_list)))


['THOR', 'HULK']


In [3]:
import numpy as np
x = np.array(["Jan", "Feb", "Mar", "Apr"])
print(x[0:4])


['Jan' 'Feb' 'Mar' 'Apr']


In [4]:
datacamp = {'course':'python', 'level':'intermediate'}
datacamp['course']

'python'

In [3]:
x = [1,2,3,4]
mult = {i: i * 3 for i in x}
print (mult)
print (type(mult))


{1: 3, 2: 6, 3: 9, 4: 12}
<class 'dict'>


In [7]:
matrix = [[col for col in range(1, 4)] for row in range(3)]
print(matrix)

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]


In [5]:
p = [[20, "A", "B"],["C", 22, 18], ["D", "E", "F"]]
print(p[1][0:2])

['C', 22]


In [7]:
capitals = {'Australia':'Canberra', 'Belgium':'Brussels', 'Finland':'Helsinki'}
for key, value in capitals.items():
    print(key, value)

Australia Canberra
Belgium Brussels
Finland Helsinki


In [6]:
#lambda functions and error - handling

x = ['cry', 'myth', 'aqua', 'ciao']
n_vowel = map(lambda w: w.count('a'), x)
print(list(n_vowel))
                                

[0, 0, 2, 1]


In [15]:
matrix = [[col for col in range(1,5)] for row in range(4)]
print(matrix)

[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]


In [7]:
from functools import reduce
product = [10,1,4]
result = reduce(lambda x, y: x * y, product)
print(result)

40


In [2]:
x = [8, 'M', 'N', 3, 1, 'A']
integers = [j for j in x if type(j) == str]
print(integers)

['M', 'N', 'A']


In [21]:
#build a generator function to convert uppercase

ef to_upper(heroes):
    for i in heroes:
        yield i.upper()

superhero_list = ['thor', 'hulk']
print(list(to_upper(superhero_list)))

['THOR', 'HULK']


In [22]:
#Use Lambda functions and count chars in list of strings

x = ['cry','myth','aqua', 'ciao']
n_vowel = map(lambda w: w.count('a'),x)
print(list(n_vowel))


[0, 0, 2, 1]


In [9]:
flash_vil = ['Mick', 'Leonard', 'Gorilla']
for x, y in enumerate(flash_vil):
    print(str(x) + ': ' + y)
    

0: Mick
1: Leonard
2: Gorilla


In [4]:
import numpy as np
store = np.array([7,8,4,6])
cost = np.array([76,87,68,88])
np_cols = np.column_stack((store, cost))
print(np_cols)



[[ 7 76]
 [ 8 87]
 [ 4 68]
 [ 6 88]]


In [8]:
import numpy as np
np_heights = np.array([[1.6,1.75],[1.56,17],[1.49,1.68]])
print(np.center(np_heights[:0]))


AttributeError: module 'numpy' has no attribute 'center'

In [9]:
import numpy as np
m = np.array([6,2,4])
n = 2
print(m+n)


[8 4 6]


In [8]:
#list compreshensions and generators

x = [1,2,3,4]
mult = {i: 3 * i for i in x }
print (x)

[1, 2, 3, 4]


In [7]:
capitals = {'Australia':'Canberra', 'Belgium':'Brussels', 'Finland':'helsinki'}

for key, value in capitals.items():
    print(key, value)

Australia Canberra
Belgium Brussels
Finland helsinki


In [6]:
flash_vil = ['Mick', 'Leonard', 'Gorilla']
for x, y in enumerate(flash_vil):
    print(str(x) + ': ' + y)

0: Mick
1: Leonard
2: Gorilla


In [3]:
import numpy as np
z = np.array([[1,1,1], 
              [3,4,4]])
# print(z)
print(z[1:,:1])

[[3]]


In [5]:
print((4 * 5) **2)

400


In [7]:
superhero_list = ['thor', 'hulk']

def to_upper(heroes):
    for i in heroes:
        yield str(i).upper()
        
print(list(to_upper(superhero_list)))

['THOR', 'HULK']


In [6]:
def square(y):
    x = y **2
    return x

print(square(5))


25


In [3]:
### Example of reduce function with a Lambda function  ###
### 25-Nov-2025 ###

from functools import reduce
product = [10,1,4]
result = reduce(lambda x, y: x * y, product)
print(result)

40


In [4]:
### Example of map function with a Lambda function  ###
### 25-Nov-2025 ###

x = ['cry', 'myth', 'aqua', 'ciao']
n_vowel = map(lambda w: w.count('a'), x)
print(list(n_vowel))

[0, 0, 2, 1]


In [13]:
y = range(0,6)
print (sum(y))

15


In [3]:
'three' > 'four'

True

In [11]:
x = 8
print(x % 7 + 6)

7


In [8]:
print ("6")
print ("6" * (2 ** 2))
print ("6" * 4)
print (6 * 4)

6
6666
6666
24


In [ ]:
# 29-Oct Databrame clensing 

# Store length of each row in survey_response column
resp_length = airlines['survey_response'].str.len()

# Find rows in airlines where resp_length > 40
airlines_survey = airlines[resp_length > 40]

# Assert minimum survey_response length is > 40
assert airlines_survey['survey_response'].str.len().min() > 40

# Print new survey_response column
print(airlines_survey['survey_response'])

In [3]:
# 28-Oct
sorted([-1,3,-2], reverse = True)

x = "python" + " exercise"
print(x.capitalize())

Python exercise


In [5]:
#28 - Oct

n = [[2,4,2], [2,6,4],[6,2,4]]
print(len(n))


3


In [7]:
def sorted_elements(x, desc=True, n=2):
    new_x = sorted(x, reverse=desc) [0:n]
    return new_x


a = [0, 6, 11, 1, 0, 10]
print(sorted_elements(a, n=3))

[11, 10, 6]


In [ ]:


# Strip duration of minutes
ride_sharing['duration_trim'] = ride_sharing['duration'].str.strip('minutes') 

# Convert duration to integer
ride_sharing['duration_time'] = ride_sharing['duration_trim'].astype('int')

# Assert the conversion was successful
assert ride_sharing['duration_time'].dtype == 'int'



In [1]:
import sys

print("Python version")
print(sys.version)
print("Version info.")
print(sys.version_info)


Python version
3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]
Version info.
sys.version_info(major=3, minor=12, micro=4, releaselevel='final', serial=0)


In [2]:
data = [1,2,3,4,2,1]
print (data)
data.remove(1)
print(data)


[1, 2, 3, 4, 2, 1]
[2, 3, 4, 2, 1]


In [12]:
print(type(type(bool("1"))))
print(3/8)


<class 'type'>
0.375


In [17]:
letters = ['A','B','C']
print (letters)

pairs = []
for letter in letters:
    for num in range(0,2): 
        pairs.append((letter, num))

print (pairs)

['A', 'B', 'C']
[('A', 0), ('A', 1), ('B', 0), ('B', 1), ('C', 0), ('C', 1)]


In [10]:
x = [3, -1, -10, 2, 7]
filter_positives = filter (lambda n: n> 0, x)
print(list(filter_positives))


[3, 2, 7]


In [12]:
#dictionary examples

practice = {'python': 100, 'r': 30, 'sql': 10}
for key, value in practice.items():
    print(key + " practice has " + str(value) + " items")
    

python practice has 100 items
r practice has 30 items
sql practice has 10 items


In [18]:
#dictionary examples

code_names = ['Spartan', 'Green Arrow']
character_names = ['John Diggle', 'Oliver Queen']

team_arrow = zip (code_names, character_names)
print(type(team_arrow))

cname, names = zip (*team_arrow)
print (names)


<class 'zip'>
('John Diggle', 'Oliver Queen')


In [23]:
#convert single dimention list into Dictionary with index numbers as key

lash_vil = ['Mick Rory', 'Lenard', 'Forilla']
for x, y in enumerate(flash_vil):
    print(str(x) + ':' + y)
    

0:Mick Rory
1:Lenard
2:Forilla


In [6]:
p=[1,16,13]
print (sorted(p, reverse=False))

[1, 13, 16]


In [10]:
list = [1,2,3,-2,-6,-4,-5]
list.index(3)

2

In [16]:
#Example of lists compressions (i think they call it)

x = [1, 'A',2,'B',3,'C']
strings = [y for y in x if type(y) == str]
print (strings)

['A', 'B', 'C']
